import { PERMISSIONS, ROLES } from "../constants/domain.js";

const MATRIX = {
  [ROLES.ADMIN]: new Set(Object.values(PERMISSIONS)),

  [ROLES.CLIENT]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_ARCHIVE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_ASSIGN_OWNER,
    PERMISSIONS.CRM_MERGE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.CRM_AUTO_ASSIGN,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TEAM_VIEW
  ]),

  // Manager: full CRM control + monitoring + delete + Chat assignment/transfer + Ticket assignment
  [ROLES.MANAGER]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_ARCHIVE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_ASSIGN_OWNER,
    PERMISSIONS.CRM_MERGE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.CRM_AUTO_ASSIGN,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TEAM_VIEW
  ]),

  // Sales: Full CRM control + Chat access + Ticket access
  [ROLES.SALES]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_ARCHIVE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_ASSIGN_OWNER,
    PERMISSIONS.CRM_MERGE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.CRM_AUTO_ASSIGN,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]),

  // Agent: Tickets access + CRM access (view, create, update)
  [ROLES.AGENT]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW
  ]),

  [ROLES.ACCOUNTS]: new Set([
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.INVOICE_MANAGE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ACTIVITY_VIEW
  ]),

  [ROLES.USER]: new Set([
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW
  ])
};

export function hasPermission(user, permission) {
  if (user?.role === "admin") return true; // Super Admin has access to all actions
  if (!user?.role) return false;

  // 1. Check custom dynamic permissions if present
  if (Array.isArray(user.permissions) && user.permissions.includes(permission)) {
    return true;
  }

  // 2. Fallback to static matrix for built-in roles
  return MATRIX[user.role]?.has(permission) || false;
}
