import { InventoryItem } from "../models/InventoryItem.js";
import { PurchaseOrder } from "../models/PurchaseOrder.js";
import { Supplier } from "../models/Supplier.js";
import { checkAndNotifyLowStock } from "./procurementNotificationService.js";

/**
 * Periodically check for low stock and automate draft PO creation
 */
export async function runStockCheck() {
  try {
    console.log("[StockWatcher] Starting inventory health check...");
    
    // Find all active items where quantity is at or below reorder level
    const lowStockItems = await InventoryItem.find({
      isActive: true,
      $expr: { $lte: ["$quantity", "$reorderLevel"] }
    });

    console.log(`[StockWatcher] Found ${lowStockItems.length} low-stock items.`);

    for (const item of lowStockItems) {
      // 1. Notify (this will trigger email/socket if threshold just hit)
      await checkAndNotifyLowStock(item._id);

      // 2. Automated PO Drafting
      if (item.preferredSupplierId) {
        // Check if a PO already exists for this item to avoid duplicates
        // Statuses to ignore: draft, sent, accepted, shipped
        const existingPO = await PurchaseOrder.findOne({
          websiteId: item.websiteId,
          supplierId: item.preferredSupplierId,
          status: { $in: ["draft", "sent", "accepted", "shipped"] },
          "items.itemId": item._id
        });

        if (!existingPO) {
          console.log(`[StockWatcher] Auto-drafting PO for item: ${item.name}`);
          
          // Generate a PO number
          const poNumber = `AUTO-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
          
          // Calculate reorder quantity (e.g., 2x reorderLevel or a fixed amount)
          const reorderQty = Math.max(item.reorderLevel * 2, 10);

          await PurchaseOrder.create({
            poNumber,
            websiteId: item.websiteId,
            supplierId: item.preferredSupplierId,
            status: "draft",
            items: [{
              itemId: item._id,
              name: item.name,
              description: `Automated restock for ${item.name}`,
              quantity: reorderQty,
              unitPrice: item.unitCost || 0,
              total: (item.unitCost || 0) * reorderQty
            }],
            total: (item.unitCost || 0) * reorderQty,
            notes: "Automatically generated by StockWatcher due to low inventory levels.",
            expectedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 1 week from now
          });
        }
      }
    }
  } catch (error) {
    console.error("[StockWatcher] Error during stock check:", error);
  }
}

/**
 * Initialize the stock watcher
 * Runs every hour
 */
export function startStockWatcher() {
  // Run once on startup
  runStockCheck();
  
  // Set interval (3600000ms = 1 hour)
  setInterval(runStockCheck, 3600000);
  console.log("[StockWatcher] Service initialized (1h interval)");
}
