import mongoose from "mongoose";
import { CustomCrmModule } from "../models/CustomCrmModule.js";
import asyncHandler from "../utils/asyncHandler.js";
import AppError from "../utils/AppError.js";
import { logAuditEvent } from "../services/auditService.js";

const DEFAULT_MODULES = [
  {
    moduleKey: "corporate_fleet_management",
    moduleName: "Corporate Vehicle & Fleet Tracker",
    description: "Track company executive vehicles, registration renewals, insurance policies, and maintenance costs.",
    apiEndpoint: "/api/custom-crm-modules/corporate_fleet_management",
    isMenuEnabled: true,
    fields: [
      { fieldKey: "plateNumber", fieldName: "Vehicle Plate Number", fieldType: "text", required: true },
      { fieldKey: "modelYear", fieldName: "Make & Model Year", fieldType: "text", required: true },
      { fieldKey: "registrationExpiry", fieldName: "Registration Expiry Date", fieldType: "date", required: true },
      { fieldKey: "assignedDriver", fieldName: "Assigned Executive Consultant", fieldType: "text", required: false }
    ],
    records: [
      { recordData: { plateNumber: "DXB-90812", modelYear: "2025 Lexus LX600", registrationExpiry: "2026-11-15", assignedDriver: "Tareq Al-Maktoum" }, createdAt: new Date() }
    ]
  },
  {
    moduleKey: "hardware_asset_vault",
    moduleName: "Enterprise IT Hardware Asset Vault",
    description: "Track company laptops, servers, security dongles, and hardware serial numbers assigned to consultants.",
    apiEndpoint: "/api/custom-crm-modules/hardware_asset_vault",
    isMenuEnabled: true,
    fields: [
      { fieldKey: "serialNumber", fieldName: "Hardware Serial Number", fieldType: "text", required: true },
      { fieldKey: "deviceCategory", fieldName: "Device Category", fieldType: "select", options: ["MacBook M3 Max", "Dell Precision", "YubiKey 5C"], required: true },
      { fieldKey: "purchaseValueAed", fieldName: "Purchase Value (AED)", fieldType: "number", required: true }
    ],
    records: [
      { recordData: { serialNumber: "APPLE-M3X-9901", deviceCategory: "MacBook M3 Max", purchaseValueAed: 14500 }, createdAt: new Date() }
    ]
  }
];

export const getCustomModulesOverview = asyncHandler(async (req, res) => {
  let count = await CustomCrmModule.countDocuments({});

  if (count === 0) {
    await CustomCrmModule.insertMany(DEFAULT_MODULES.map(m => ({ ...m, createdBy: req.user._id })));
  }

  const modules = await CustomCrmModule.find({}).sort({ createdAt: -1 });

  let totalRecords = 0;
  modules.forEach(m => {
    totalRecords += (m.records || []).length;
  });

  return res.json({
    summary: {
      totalCustomModules: modules.length,
      autoGeneratedApis: modules.length,
      totalCustomRecordsCount: totalRecords,
      engineStatus: "DYNAMIC_MODULE_ENGINE_ACTIVE"
    },
    modules
  });
});

export const createCustomModule = asyncHandler(async (req, res) => {
  const { moduleKey, moduleName, description, fields } = req.body;

  if (!moduleKey || !moduleName) {
    throw new AppError("Module key and module title are required", 400);
  }

  const cleanKey = moduleKey.toLowerCase().replace(/[^a-z0-9_]/g, "_");

  const existing = await CustomCrmModule.findOne({ moduleKey: cleanKey });
  if (existing) throw new AppError("Custom module with this key already exists", 400);

  const newModule = await CustomCrmModule.create({
    moduleKey: cleanKey,
    moduleName,
    description: description || "",
    apiEndpoint: `/api/custom-crm-modules/${cleanKey}`,
    fields: Array.isArray(fields) && fields.length > 0 ? fields : [
      { fieldKey: "title", fieldName: "Record Title", fieldType: "text", required: true },
      { fieldKey: "status", fieldName: "Status", fieldType: "select", options: ["Draft", "Active"], required: false }
    ],
    records: [],
    createdBy: req.user._id
  });

  await logAuditEvent({
    userId: req.user._id,
    websiteId: null,
    action: "CUSTOM_CRM_MODULE_GENERATED",
    resource: "CustomCrmModule",
    resourceId: newModule._id,
    ipAddress: req.ip,
    userAgent: req.get("user-agent"),
    changes: { moduleKey: newModule.moduleKey, moduleName: newModule.moduleName, apiEndpoint: newModule.apiEndpoint }
  });

  return res.status(201).json(newModule);
});

export const addModuleRecord = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { recordData } = req.body;

  const moduleDoc = await CustomCrmModule.findById(id);
  if (!moduleDoc) throw new AppError("Custom module not found", 404);

  moduleDoc.records.unshift({
    recordData: recordData || {},
    createdAt: new Date()
  });

  await moduleDoc.save();

  await logAuditEvent({
    userId: req.user._id,
    websiteId: null,
    action: "CUSTOM_CRM_MODULE_RECORD_ADDED",
    resource: "CustomCrmModule",
    resourceId: moduleDoc._id,
    ipAddress: req.ip,
    userAgent: req.get("user-agent"),
    changes: { moduleKey: moduleDoc.moduleKey, recordData }
  });

  return res.status(201).json(moduleDoc);
});

export const deleteCustomModule = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const moduleDoc = await CustomCrmModule.findByIdAndDelete(id);

  if (!moduleDoc) throw new AppError("Module not found", 404);

  await logAuditEvent({
    userId: req.user._id,
    websiteId: null,
    action: "CUSTOM_CRM_MODULE_DELETED",
    resource: "CustomCrmModule",
    resourceId: moduleDoc._id,
    ipAddress: req.ip,
    userAgent: req.get("user-agent"),
    changes: { moduleKey: moduleDoc.moduleKey }
  });

  return res.json({ message: "Custom module deleted successfully" });
});
